# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  github-mcp-server = {
    pname = "github-mcp-server";
    version = "v0.32.0";
    src = fetchFromGitHub {
      owner = "github";
      repo = "github-mcp-server";
      rev = "v0.32.0";
      fetchSubmodules = false;
      sha256 = "sha256-BD/t3UBAvrzJpRI7b06FjE8c+vzdQiXsj6eiUGQX6uA=";
    };
  };
}
