# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  context7-mcp = {
    pname = "context7-mcp";
    version = "2.1.4";
    src = fetchurl {
      url = "https://registry.npmjs.org/@upstash/context7-mcp/-/context7-mcp-2.1.4.tgz";
      sha256 = "sha256-G3ZrnUP0QUngr8vDZq/3UoSls4lX00+aQ0vUdeBGvA0=";
    };
  };
  mcp-proxy = {
    pname = "mcp-proxy";
    version = "0.11.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/m/mcp_proxy/mcp_proxy-0.11.0.tar.gz";
      sha256 = "sha256-NCTssfV/gXRiXd/w3xW1NKCHGdh89fnWorHgON5pafE=";
    };
  };
  effect-mcp = {
    pname = "effect-mcp";
    version = "0.1.16";
    src = fetchurl {
      url = "https://registry.npmjs.org/effect-mcp/-/effect-mcp-0.1.16.tgz";
      sha256 = "sha256-k36Ucri8CAw+xwVVKt58jwkjNlBF79KgHYr9v2lRvk8=";
    };
  };
  mcp-server-fetch = {
    pname = "mcp-server-fetch";
    version = "2025.4.7";
    src = fetchurl {
      url = "https://pypi.org/packages/source/m/mcp_server_fetch/mcp_server_fetch-2025.4.7.tar.gz";
      sha256 = "sha256-VieePFXLHlBrlYypuyPtRBOUSm8jC8oh4ESu5Rc0/kc=";
    };
  };
}
